import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Sackett Ranch Monarch Butterfly Recovery Center</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Sackett Ranch Monarch Butterfly Recovery Center" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="author" content="Sackett Ranch Monarch Butterfly Recovery Center" />
        <meta name="copyright" content="Sackett Ranch Monarch Butterfly Recovery Center" />
        <meta name="application-name" content="Sackett Ranch Monarch Butterfly Recovery Center" />
        <meta name="apple-mobile-web-app-title" content="Sackett Ranch" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/path/to/tile-image.png" />
        <meta name="msapplication-config" content="/path/to/browserconfig.xml" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="og:title" content="Sackett Ranch Monarch Butterfly Recovery Center" />
        <meta name="keywords" content="Sackett Ranch, Monarch Butterfly, Recovery Center, Conservation, Nature" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@center_twitter_handle" />
        <meta name="twitter:title" content="Sackett Ranch Monarch Butterfly Recovery Center" />
        <meta name="twitter:description" content="Sackett Ranch Monarch Butterfly Recovery Center" />
        <meta name="twitter:image" content="/path/to/image.jpg" />
        <meta name="twitter:creator" content="@center_twitter_handle" />
        <meta name="robots" content="index, follow" />
        <meta name="google-site-verification" content="your-google-site-verification-code" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <link rel="shortcut icon" href="/favicon.ico" />
        {/* Shopify Buy Button JS SDK */}
        <script async src="https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js"></script>
        <script async src="https://sdks.shopifycdn.com/buy-button-storefront/latest/buybutton-storefront.min.js"></script>
        {/* Google Tag Manager */}
        <script async>
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-MMJPJJDR');`}
        </script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
